"""Shared domain contracts for the OCR service."""

from .errors import (
    CandidateCollectionErrorCode,
    CandidateCollectionFailure,
    ConfigurationError,
    DomainError,
    FileIntakeErrorCode,
    FileIntakeFailure,
    InputValidationError,
    LeaseConflictError,
    MinerUErrorCode,
    MinerUFailure,
    MergeErrorCode,
    MergeFailure,
    PersistenceError,
    SecondaryOcrErrorCode,
    SecondaryOcrFailure,
    StateTransitionError,
)
from .files import IncomingFile, StoredFile, SupportedMediaType
from .models import (
    BatchStatus,
    FileStatus,
    ProcessingStage,
    SecondaryOCREngine,
    new_id,
    utc_now,
)
from .merge import (
    MergePublicationResult,
    ReplacementAuditRecord,
    ReplacementDecision,
    ReplacementReason,
    RollbackPublicationResult,
)
from .mineru import (
    MinerUDocumentResult,
    MinerUParseRequest,
    MinerUProgress,
    MinerUProgressStatus,
    MinerUSubmission,
)
from .tasks import BatchSnapshot, CreateBatchResult, FileTaskSnapshot, LeaseClaim
from .secondary_ocr import (
    CandidateCollection,
    CandidateReference,
    CandidateSourceKind,
    ImageCandidate,
    MinerUImageFormat,
    OrthogonalAngle,
    SecondaryContentFormat,
    SecondaryOcrProvider,
    SecondaryOcrResult,
    SecondaryProcessingRecord,
    SecondaryProcessingStatus,
    SecondaryResultKind,
    SecondaryResultState,
)

__all__ = [
    "BatchStatus",
    "BatchSnapshot",
    "CandidateCollection",
    "CandidateCollectionErrorCode",
    "CandidateCollectionFailure",
    "CandidateReference",
    "CandidateSourceKind",
    "ConfigurationError",
    "DomainError",
    "FileIntakeErrorCode",
    "FileIntakeFailure",
    "FileStatus",
    "InputValidationError",
    "IncomingFile",
    "ImageCandidate",
    "LeaseClaim",
    "LeaseConflictError",
    "MinerUDocumentResult",
    "MinerUErrorCode",
    "MinerUFailure",
    "MergeErrorCode",
    "MergeFailure",
    "MergePublicationResult",
    "MinerUParseRequest",
    "MinerUProgress",
    "MinerUProgressStatus",
    "MinerUSubmission",
    "MinerUImageFormat",
    "OrthogonalAngle",
    "PersistenceError",
    "ProcessingStage",
    "ReplacementAuditRecord",
    "ReplacementDecision",
    "ReplacementReason",
    "RollbackPublicationResult",
    "SecondaryOCREngine",
    "SecondaryOcrErrorCode",
    "SecondaryOcrFailure",
    "SecondaryContentFormat",
    "SecondaryOcrProvider",
    "SecondaryOcrResult",
    "SecondaryProcessingRecord",
    "SecondaryProcessingStatus",
    "SecondaryResultKind",
    "SecondaryResultState",
    "StateTransitionError",
    "StoredFile",
    "SupportedMediaType",
    "CreateBatchResult",
    "FileTaskSnapshot",
    "new_id",
    "utc_now",
]
