"""Service-wide capacity and retention defaults."""

SUPPORTED_EXTENSIONS = frozenset({".pdf", ".png", ".jpg", ".jpeg"})

DEFAULT_MAX_FILES = 20
DEFAULT_MAX_FILE_SIZE_BYTES = 60 * 1024 * 1024
DEFAULT_MAX_PAGES = 500
DEFAULT_MAX_BATCH_SIZE_BYTES = 1024**3

DEFAULT_INPUT_RETENTION_HOURS = 24
DEFAULT_INTERMEDIATE_RETENTION_HOURS = 24
DEFAULT_RESULT_RETENTION_HOURS = 24
DEFAULT_AUDIT_METADATA_RETENTION_DAYS = 30
